# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spark/spark_ws.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'spark/spark_ws.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from spark import spark_pb2 as spark_dot_spark__pb2
from spark import spark_sampler_pb2 as spark_dot_spark__sampler__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14spark/spark_ws.proto\x12\x05spark\x1a\x11spark/spark.proto\x1a\x19spark/spark_sampler.proto\"T\n\tRawPacket\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x12\n\npublic_key\x18\x02 \x01(\x0c\x12\x11\n\tsignature\x18\x03 \x01(\x0c\x12\x0f\n\x07message\x18\x04 \x01(\x0c\"\xe2\x02\n\rPacketWrapper\x12(\n\x0bserver_pong\x18\x01 \x01(\x0b\x32\x11.spark.ServerPongH\x00\x12?\n\x17server_connect_response\x18\x02 \x01(\x0b\x32\x1c.spark.ServerConnectResponseH\x00\x12?\n\x15server_update_sampler\x18\x03 \x01(\x0b\x32\x1e.spark.ServerUpdateSamplerDataH\x00\x12\x41\n\x18server_update_statistics\x18\x04 \x01(\x0b\x32\x1d.spark.ServerUpdateStatisticsH\x00\x12(\n\x0b\x63lient_ping\x18\n \x01(\x0b\x32\x11.spark.ClientPingH\x00\x12.\n\x0e\x63lient_connect\x18\x0b \x01(\x0b\x32\x14.spark.ClientConnectH\x00\x42\x08\n\x06packet\"&\n\nServerPong\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x05\"\xa6\x02\n\x15ServerConnectResponse\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x31\n\x05state\x18\x02 \x01(\x0e\x32\".spark.ServerConnectResponse.State\x12\x37\n\x08settings\x18\x03 \x01(\x0b\x32%.spark.ServerConnectResponse.Settings\x12\x17\n\x0flast_payload_id\x18\x04 \x01(\t\x1a\x41\n\x08Settings\x12\x1b\n\x13statistics_interval\x18\x01 \x01(\x05\x12\x18\n\x10sampler_interval\x18\x02 \x01(\x05\"2\n\x05State\x12\x0c\n\x08\x41\x43\x43\x45PTED\x10\x00\x12\r\n\tUNTRUSTED\x10\x01\x12\x0c\n\x08REJECTED\x10\x02\"-\n\x17ServerUpdateSamplerData\x12\x12\n\npayload_id\x18\x01 \x01(\t\"n\n\x16ServerUpdateStatistics\x12+\n\x08platform\x18\x01 \x01(\x0b\x32\x19.spark.PlatformStatistics\x12\'\n\x06system\x18\x02 \x01(\x0b\x32\x17.spark.SystemStatistics\"7\n\rClientConnect\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"&\n\nClientPing\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x05\x42,\n\x14me.lucko.spark.protoB\x14SparkWebSocketProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spark.spark_ws_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024me.lucko.spark.protoB\024SparkWebSocketProtos'
  _globals['_RAWPACKET']._serialized_start=77
  _globals['_RAWPACKET']._serialized_end=161
  _globals['_PACKETWRAPPER']._serialized_start=164
  _globals['_PACKETWRAPPER']._serialized_end=518
  _globals['_SERVERPONG']._serialized_start=520
  _globals['_SERVERPONG']._serialized_end=558
  _globals['_SERVERCONNECTRESPONSE']._serialized_start=561
  _globals['_SERVERCONNECTRESPONSE']._serialized_end=855
  _globals['_SERVERCONNECTRESPONSE_SETTINGS']._serialized_start=738
  _globals['_SERVERCONNECTRESPONSE_SETTINGS']._serialized_end=803
  _globals['_SERVERCONNECTRESPONSE_STATE']._serialized_start=805
  _globals['_SERVERCONNECTRESPONSE_STATE']._serialized_end=855
  _globals['_SERVERUPDATESAMPLERDATA']._serialized_start=857
  _globals['_SERVERUPDATESAMPLERDATA']._serialized_end=902
  _globals['_SERVERUPDATESTATISTICS']._serialized_start=904
  _globals['_SERVERUPDATESTATISTICS']._serialized_end=1014
  _globals['_CLIENTCONNECT']._serialized_start=1016
  _globals['_CLIENTCONNECT']._serialized_end=1071
  _globals['_CLIENTPING']._serialized_start=1073
  _globals['_CLIENTPING']._serialized_end=1111
# @@protoc_insertion_point(module_scope)
