# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spark/spark_heap.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'spark/spark_heap.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from spark import spark_pb2 as spark_dot_spark__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16spark/spark_heap.proto\x12\x05spark\x1a\x11spark/spark.proto\"T\n\x08HeapData\x12%\n\x08metadata\x18\x01 \x01(\x0b\x32\x13.spark.HeapMetadata\x12!\n\x07\x65ntries\x18\x02 \x03(\x0b\x32\x10.spark.HeapEntry\"\x8e\x05\n\x0cHeapMetadata\x12-\n\x07\x63reator\x18\x01 \x01(\x0b\x32\x1c.spark.CommandSenderMetadata\x12\x32\n\x11platform_metadata\x18\x02 \x01(\x0b\x32\x17.spark.PlatformMetadata\x12\x36\n\x13platform_statistics\x18\x03 \x01(\x0b\x32\x19.spark.PlatformStatistics\x12\x32\n\x11system_statistics\x18\x04 \x01(\x0b\x32\x17.spark.SystemStatistics\x12\x16\n\x0egenerated_time\x18\x05 \x01(\x03\x12L\n\x15server_configurations\x18\x06 \x03(\x0b\x32-.spark.HeapMetadata.ServerConfigurationsEntry\x12\x31\n\x07sources\x18\x07 \x03(\x0b\x32 .spark.HeapMetadata.SourcesEntry\x12O\n\x17\x65xtra_platform_metadata\x18\x08 \x03(\x0b\x32..spark.HeapMetadata.ExtraPlatformMetadataEntry\x1a;\n\x19ServerConfigurationsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1aJ\n\x0cSourcesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12)\n\x05value\x18\x02 \x01(\x0b\x32\x1a.spark.PluginOrModMetadata:\x02\x38\x01\x1a<\n\x1a\x45xtraPlatformMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"I\n\tHeapEntry\x12\r\n\x05order\x18\x01 \x01(\x05\x12\x11\n\tinstances\x18\x02 \x01(\x05\x12\x0c\n\x04size\x18\x03 \x01(\x03\x12\x0c\n\x04type\x18\x04 \x01(\tB\'\n\x14me.lucko.spark.protoB\x0fSparkHeapProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spark.spark_heap_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024me.lucko.spark.protoB\017SparkHeapProtos'
  _globals['_HEAPMETADATA_SERVERCONFIGURATIONSENTRY']._loaded_options = None
  _globals['_HEAPMETADATA_SERVERCONFIGURATIONSENTRY']._serialized_options = b'8\001'
  _globals['_HEAPMETADATA_SOURCESENTRY']._loaded_options = None
  _globals['_HEAPMETADATA_SOURCESENTRY']._serialized_options = b'8\001'
  _globals['_HEAPMETADATA_EXTRAPLATFORMMETADATAENTRY']._loaded_options = None
  _globals['_HEAPMETADATA_EXTRAPLATFORMMETADATAENTRY']._serialized_options = b'8\001'
  _globals['_HEAPDATA']._serialized_start=52
  _globals['_HEAPDATA']._serialized_end=136
  _globals['_HEAPMETADATA']._serialized_start=139
  _globals['_HEAPMETADATA']._serialized_end=793
  _globals['_HEAPMETADATA_SERVERCONFIGURATIONSENTRY']._serialized_start=596
  _globals['_HEAPMETADATA_SERVERCONFIGURATIONSENTRY']._serialized_end=655
  _globals['_HEAPMETADATA_SOURCESENTRY']._serialized_start=657
  _globals['_HEAPMETADATA_SOURCESENTRY']._serialized_end=731
  _globals['_HEAPMETADATA_EXTRAPLATFORMMETADATAENTRY']._serialized_start=733
  _globals['_HEAPMETADATA_EXTRAPLATFORMMETADATAENTRY']._serialized_end=793
  _globals['_HEAPENTRY']._serialized_start=795
  _globals['_HEAPENTRY']._serialized_end=868
# @@protoc_insertion_point(module_scope)
